### ISSUE TITLE
UnicodeDecodeError in mysqldump_to_csv.py

### ISSUE THREAD

**Issue by mtmail** [osm-search/wikipedia-wikidata#27]
Need to figure out if this  stops the script and leaves the output file incomplete. For all languages so far only the langlinks files seem affected.

```
[01:40:48] [language bg] langlinks table SQL => CSV
[01:40:52] Traceback (most recent call last):
[01:40:52]   File "bin/mysqldump_to_csv.py", line 114, in <module>
[01:40:52]     main()
[01:40:52]   File "bin/mysqldump_to_csv.py", line 104, in main
[01:40:52]     for line in fileinput.input():
[01:40:52]   File "/usr/lib/python3.8/fileinput.py", line 248, in __next__
[01:40:52]     line = self._readline()
[01:40:52]   File "/usr/lib/python3.8/codecs.py", line 322, in decode
[01:40:52]     (result, consumed) = self._buffer_decode(data, self.errors, final)
[01:40:52] UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 690-691: invalid continuation byte
```

**Comment by mtmail** [comment]
The error indeed stops the script, leading to incomplete output.

Expected is about 300 languages
```
zcat downloaded/wikipedia/bg/langlinks.sql.gz | perl -pe's/\),\(/),\n(/g' | grep '^(' | cut -d\, -f2 | sort | uniq -c
    979 'xh'
  15903 'xmf'
   8511 'yi'
  13097 'yo'
   1945 'za'
   2473 'zea'
 156476 'zh'
   5135 'zh-classical'
      1 'zh-cn'
  53119 'zh-min-nan'
      1 'zh-tw'
  45185 'zh-yue'
   2978 'zu'

334 lines
```

but mysqldump_to_csv.py only prints 10%

```
zcat downloaded/wikipedia/bg/langlinks.sql.gz | python3 bin/mysqldump_to_csv.py | cut -d, -f2 | sort | uniq -c

   4138 ban
  15933 bar
   5547 bat-smg
   6511 bcl
  83569 be
      8 be-tarask
  49290 be-x-old
   8304 bh

34 lines
```

**Comment by mtmail** [comment]
Fixed by https://github.com/osm-search/wikipedia-wikidata/pull/34
