### ISSUE TITLE
SPARQL queries for wikidata types can timeout

### ISSUE THREAD

**Issue by mtmail** [osm-search/wikipedia-wikidata#4]
https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service queries we run in the "Get wikidata places from wikidata query API" step sometimes produce incomplete (JSON) output:

`tail -1000 *Q811979*.json`
```
#     }, {
#       "item" : {
#         "type" : "uri",
#         "value" : "SPARQL-QUERY: queryStr=SELECT ?item WHERE{?item wdt:P31*/wdt:P279*wd:Q811979;}
# java.util.concurrent.TimeoutException
# 	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
# 	at com.bigdata.rdf.sail.webapp.BigdataServlet.submitApiTask(BigdataServlet.java:292)
```

which in the next step produces a warning, e.g. `parse error: Invalid numeric literal at line 7154740, column 18` but the script just continues.

```
grep -c TimeoutException *.json | grep -v ':0'
tmp_Q15324.json:1
tmp_Q17334923.json:1
tmp_Q177634.json:1
tmp_Q271669.json:1
tmp_Q3257686.json:1
tmp_Q41176.json:1
tmp_Q43229.json:1
tmp_Q486972.json:1
tmp_Q532.json:1
tmp_Q811979.json:1
tmp_Q82794.json:1
```
Add proper checks for the output and HTTP status in the loop, possibly abort or retry behaviour and check the limits in https://www.mediawiki.org/wiki/Wikidata_Query_Service/User_Manual#Query_limits are observed. Maybe the queries can be split into sub-types.

**Comment by mtmail** [comment]
fixed by https://github.com/osm-search/wikipedia-wikidata/pull/14
